# Generated by Django 5.0 on 2026-01-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, help_text="E.164 dialing prefix detected from the user's location.", max_length=6, verbose_name='phone country code'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary contact phone number without the country prefix.', max_length=20, verbose_name='phone number'),
        ),
    ]
