# Generated by Django 5.0 on 2026-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Date of the snapshot', unique=True)),
                ('snapshot_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='Type of snapshot', max_length=50)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_swipes', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('match_rate', models.FloatField(default=0.0)),
                ('conversation_rate', models.FloatField(default=0.0)),
                ('verification_rate', models.FloatField(default=0.0)),
                ('report_rate', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_subscriptions', models.IntegerField(default=0)),
                ('arpu', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('new_registrations', models.IntegerField(default=0)),
                ('growth_rate', models.FloatField(default=0.0)),
                ('metrics_data', models.JSONField(help_text='Complete metrics data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='EventConsumerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(help_text='Name of the consumer', max_length=100, unique=True)),
                ('consumer_group', models.CharField(help_text='Redis consumer group name', max_length=100)),
                ('last_processed_event_id', models.CharField(blank=True, help_text='Last processed event ID', max_length=255, null=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True, help_text='Last heartbeat from consumer')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the consumer is active')),
                ('processing_errors', models.IntegerField(default=0, help_text='Number of processing errors')),
                ('events_processed_today', models.IntegerField(default=0, help_text='Events processed today')),
                ('events_processed_this_hour', models.IntegerField(default=0, help_text='Events processed this hour')),
                ('average_processing_time', models.FloatField(default=0.0, help_text='Average processing time in seconds')),
            ],
            options={
                'ordering': ['consumer_name'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(help_text='Unique risk identifier', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Risk title', max_length=200)),
                ('category', models.CharField(help_text='Risk category', max_length=50)),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Current risk level', max_length=20)),
                ('impact_score', models.IntegerField(default=1, help_text='Impact score (1-5)')),
                ('probability_score', models.IntegerField(default=1, help_text='Probability score (1-5)')),
                ('risk_score', models.IntegerField(default=1, help_text='Calculated risk score')),
                ('description', models.TextField(help_text='Risk description')),
                ('mitigation_plan', models.JSONField(default=list, help_text='Mitigation actions')),
                ('contingency_plan', models.JSONField(default=list, help_text='Contingency plans')),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('assessing', 'Assessing'), ('mitigating', 'Mitigating'), ('monitoring', 'Monitoring'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='identified', help_text='Risk status', max_length=20)),
                ('owner', models.CharField(blank=True, help_text='Risk owner', max_length=100, null=True)),
                ('identified_date', models.DateTimeField(auto_now_add=True)),
                ('last_assessed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('related_events', models.JSONField(default=list, help_text='Related event references')),
            ],
            options={
                'ordering': ['-risk_score', '-identified_date'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Unique event identifier', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Type of event', max_length=100)),
                ('event_version', models.CharField(default='1.0', help_text='Event schema version', max_length=10)),
                ('occurred_at', models.DateTimeField(help_text='When the event occurred')),
                ('actor_id', models.CharField(blank=True, help_text='ID of the user who triggered the event', max_length=255, null=True)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the entity the event relates to', max_length=255, null=True)),
                ('correlation_id', models.CharField(blank=True, help_text='Correlation ID for event tracing', max_length=255, null=True)),
                ('payload', models.JSONField(help_text='Event payload data')),
                ('metadata', models.JSONField(default=dict, help_text='Event metadata')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the event was processed', null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Event processing status', max_length=20)),
                ('processing_attempts', models.IntegerField(default=0, help_text='Number of processing attempts')),
                ('last_error', models.TextField(blank=True, help_text='Last processing error', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='events_even_event_t_9a7c4d_idx'), models.Index(fields=['actor_id', 'occurred_at'], name='events_even_actor_i_8f964f_idx'), models.Index(fields=['processing_status', 'occurred_at'], name='events_even_process_1b78e1_idx'), models.Index(fields=['correlation_id'], name='events_even_correla_a8a32d_idx')],
            },
        ),
    ]
