# Generated by Django 5.0 on 2025-12-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_age_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('matches', 'Matches Only'), ('premium', 'Premium Users Only')], default='everyone', max_length=10),
        ),
    ]
