# Generated by Django 5.0 on 2025-12-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_is_hidden_profile_photo_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='virtual_currency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
