# Generated by Django 5.0 on 2025-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_is_online_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boost_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_reward_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completion_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
