# Generated by Django 5.0 on 2025-12-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_boost_expiry_profile_last_login_reward_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(default=10)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('boost_type', models.CharField(choices=[('visibility', 'Visibility Boost'), ('match', 'Match Boost')], default='visibility', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
