# Generated by Django 5.0 on 2025-12-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_boost_photo_is_moderated_photo_is_safe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_is_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_moderation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
