# Generated by Django 5.0 on 2025-12-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userfeaturevector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boost',
            options={'verbose_name': 'Boost', 'verbose_name_plural': 'Boosts'},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Interest', 'verbose_name_plural': 'Interests'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['is_primary', 'uploaded_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='profileinterest',
            options={'verbose_name': 'Profile Interest', 'verbose_name_plural': 'Profile Interests'},
        ),
        migrations.AlterModelOptions(
            name='userfeaturevector',
            options={'verbose_name': 'User Feature Vector', 'verbose_name_plural': 'User Feature Vectors'},
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en-us', max_length=10, verbose_name='preferred language'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='boost_type',
            field=models.CharField(choices=[('visibility', 'Visibility Boost'), ('match', 'Match Boost')], default='visibility', max_length=20, verbose_name='boost type'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='cost',
            field=models.PositiveIntegerField(default=10, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='duration (days)'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='profile_photos/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Designates if this is the user's primary profile photo.", verbose_name='is primary'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography about yourself.', max_length=500, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If checked, your profile will not be visible to other users.', verbose_name='is hidden'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='is online'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='is premium'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, verbose_name='looking for'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_age',
            field=models.PositiveIntegerField(default=100, verbose_name='maximum age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_distance',
            field=models.PositiveIntegerField(default=50, help_text='Maximum distance in km for discovering other users.', verbose_name='max distance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_age',
            field=models.PositiveIntegerField(default=18, verbose_name='minimum age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('matches', 'Matches Only'), ('premium', 'Premium Users Only')], default='everyone', max_length=10, verbose_name='photo visibility'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_completion_score',
            field=models.PositiveIntegerField(default=0, verbose_name='profile completion score'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], default='single', max_length=10, verbose_name='relationship status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='virtual_currency',
            field=models.PositiveIntegerField(default=0, verbose_name='virtual currency'),
        ),
        migrations.AlterField(
            model_name='userfeaturevector',
            name='feature_vector',
            field=models.JSONField(default=dict, verbose_name='feature vector'),
        ),
    ]
