# Generated by Django 5.0 on 2025-12-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_boost_options_alter_interest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_passport_enabled',
            field=models.BooleanField(default=False, help_text="If enabled, user's location is spoofed to passport coordinates.", verbose_name='is passport enabled'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='passport latitude'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='passport longitude'),
        ),
    ]
