# Generated by Django 5.0 on 2025-12-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_is_passport_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_music',
            field=models.TextField(blank=True, help_text='Describe your favorite music genres, artists, or songs.', verbose_name='favorite music'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prompts',
            field=models.JSONField(blank=True, default=list, help_text='User-selected prompts and their answers.', null=True, verbose_name='prompts and answers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='values',
            field=models.JSONField(blank=True, default=list, help_text="User's core values or life philosophies.", null=True, verbose_name='values'),
        ),
    ]
