# Generated by Django 5.0 on 2025-12-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_favorite_music_profile_prompts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Latitude coordinate of the user's location. Should be auto-populated by a geocoding service.", null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(help_text="User's physical location (city, state, country).", max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Longitude coordinate of the user's location. Should be auto-populated by a geocoding service.", null=True, verbose_name='longitude'),
        ),
    ]
