# Generated by Django 5.0 on 2026-01-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_latitude_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_music',
            field=models.JSONField(blank=True, default=list, help_text='List of favorite music genres, artists, or songs.', null=True, verbose_name='favorite music'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('Long-term relationship', 'Long-term relationship'), ('Short-term relationship', 'Short-term relationship'), ('Friendship', 'Friendship'), ('Casual dating', 'Casual dating')], max_length=25, verbose_name='looking for'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(choices=[('Single', 'Single'), ('In a relationship', 'In a relationship'), ('Married', 'Married')], default='Single', max_length=20, verbose_name='relationship status'),
        ),
    ]
