# Generated by Django 5.0 on 2026-01-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_profile_favorite_music_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last location update via geocoding.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en-us', 'English'), ('fr-fr', 'French'), ('es-es', 'Spanish')], default='en-us', max_length=10, verbose_name='preferred language'),
        ),
    ]
