# Generated by Django 5.0 on 2026-01-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_last_location_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the profile.', max_length=100, verbose_name='slug'),
        ),
    ]
