# Generated by Django 5.0 on 2026-01-06 19:16

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    for profile in Profile.objects.all():
        if not profile.slug:
            base_slug = slugify(profile.user.username)
            slug = base_slug
            counter = 1
            while Profile.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            profile.slug = slug
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
