# Generated by Django 5.0 on 2026-01-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the profile.', max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
