# Generated by Django 5.0 on 2026-01-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_profile_country_profile_state_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_values', to='profiles.profile')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.value')),
            ],
            options={
                'verbose_name': 'Profile Value',
                'verbose_name_plural': 'Profile Values',
                'unique_together': {('profile', 'value')},
            },
        ),
    ]
