# Generated by Django 5.0 on 2026-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_value_profilevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gender', 'Gender'), ('looking_for', 'Looking For'), ('relationship_status', 'Relationship Status'), ('language', 'Language'), ('prompt', 'Prompt')], db_index=True, max_length=50, verbose_name='category')),
                ('value', models.CharField(help_text='Internal value stored in database', max_length=200, verbose_name='value')),
                ('label', models.CharField(help_text='Display label shown to users', max_length=200, verbose_name='label')),
                ('order', models.IntegerField(default=0, help_text='Order in which options are displayed', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this option is available for selection', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['category', 'order', 'value'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='profiles_op_categor_3980d9_idx')],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
